version: "3.8"

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    command: run --host 0.0.0.0 --port 8008 --path /chroma_data
    ports:
      - "8008:8008"
    volumes:
      - ./chroma_data:/chroma_data
    environment:
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=*

  reranker:
    build: ./llm-server
    ports:
      - "8811:8811"
    depends_on:
      - chroma
      - ollama
    volumes:
      - ./chroma_data:/app/chroma_data
    environment:
      - CHROMA_URL=http://chroma:8008
      - OLLAMA_URL=http://ollama:11434

  nginx:
    image: nginx:alpine
    env_file: .env
    environment:
      - LLM_SECRET_KEY=${LLM_SECRET_KEY}
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/api.conf.template:/etc/nginx/templates/api.conf.template:ro
      - ./nginx/empty.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  ollama:
